### ISSUE TITLE
Package Cleanup Thread

### ISSUE THREAD

**Issue by acxz** [acxz/gazebo-arch#1]
This thread tracks the AUR packages which need to be imported into this repo.

We also need to discuss maintainership roles as well. This is primarily to prevent people from pushing to the same AUR package with the same change.

Essentially the AUR should only be a sync of this repo and should not be pushed directly. [`aurpublish`](https://github.com/eli-schwartz/aurpublish) will be used.

The process goes like so:
1) Commit changes to this repo
2) Use aurpublish <package_name> to publish to the AUR

List of packages to add and consolidate maintainer role

- [x] sdformat-6 (send AUR deletion request)
- [x] sdformat-8 (send AUR deletion request)
- [x] libsdformat-hg (send AUR deletion request)

- [x] ignition-cmake-0 (send AUR deletion request)

- [x] ignition-common-1 (send AUR deletion request)

- [x] ignition-fuel_tools-1 (send AUR deletion request)

- [x] ignition-math-4  (send AUR deletion request)
- [x] ignition-math-hg  (send AUR deletion request)

- [x] ignition-msgs-1  (send AUR deletion request)

- [x] ignition-transport-4 (send AUR deletion request)

**Comment by alexdewar** [comment]
Should I raise this as an issue btw?

**Comment by alexdewar** [comment]
Okey doke

**Comment by alexdewar** [comment]
Done

**Comment by bobosito000** [comment]
Hi. Thanks for letting me know bout this billy. I do not mind helping. What do you guys need with the gazebo-git package?

**Comment by bobosito000** [comment]
I would not mind giving you back ownership, if you use make instead of ninja on gazebo-git.

**Comment by acxz** [comment]
I personally prefer make over ninja, since make respects `/etc/makepkg.conf`.

**Comment by bobosito000** [comment]
Just curious, why do you use ninja instead of make in the gazebo package?

**Comment by acxz** [comment]
@bobosito000 can you make a new issue about that. I'd like for this thread to stay on topic.

**Comment by bobosito000** [comment]
Ok. I went ahead and added you as a maintainer.

**Comment by acxz** [comment]
Sweet, verified, thanks so much @bobosito000 !

**Comment by homalozoa** [comment]
Hey @acxz . I've added you into all AUR packages about ignition/sdformat I maintained. Check it please. Thanks for your helps.

**Comment by acxz** [comment]
@homalozoa would you disowning those packages as well, so that I can be the primary maintainer.

**Comment by homalozoa** [comment]
> @homalozoa would you disowning those packages as well, so that I can be the primary maintainer.

That's OK for me. I'll disown these packages.

**Comment by acxz** [comment]
Out dated packages have been deleted from the AUR.
