### ISSUE TITLE
Error build ignition-transport8

### ISSUE THREAD

**Issue by mrxiuer** [acxz/gazebo-arch#101]
When I install ignition-transport8, it reports an error: ![swappy-20240527-202327](https://github.com/acxz/gazebo-arch/assets/93573898/4fff4d80-c6c6-4cbe-9dc0-c42bb4be90d6) Does anyone know how to fix it?

**Comment by clq9920** [comment]
i also encountered this problem ：<
maybe you can download the package from https://mirrors.tuna.tsinghua.edu.cn/arch4edu/x86_64/ignition-transport-8-8.4.0-4-x86_64.pkg.tar.zst

**Comment by mrxiuer** [comment]
> 我也遇到了这个问题：<也许你可以从https://mirrors.tuna.tsinghua.edu.cn/arch4edu/x86_64/ignition-transport-8-8.4.0-4-x86_64.pkg.tar.zst 下载软件包[](https://mirrors.tuna.tsinghua.edu.cn/arch4edu/x86_64/ignition-transport-8-8.4.0-4-x86_64.pkg.tar.zst)

Thanks,it works.
