### ISSUE TITLE
Let's converging the AUR maintainer. I will orphan my ignition-* AUR packages.

### ISSUE THREAD

**Issue by AchmadFathoni** [acxz/gazebo-arch#15]
Since now, I'm not active using ignition-* packages anymore. I will orphan those packages so the maintainer will be less convoluted. You can add me as co-maintainer instead if you need help. That includes

```
ignition-cmake
ignition-common
ignition-math
```

**Comment by acxz** [comment]
Thanks so much @AchmadFathoni , thanks for maintaining them!
