### ISSUE TITLE
[ignition-gazebo] fails: repo gazebosim/gz-gazebo has been removed?

### ISSUE THREAD

**Issue by Maik93** [acxz/gazebo-arch#29]
Hi,
I have just noticed that `ignition-gazebo` cannot be compiled, since that the repository stated in the PKGBUILD seems to not exist any more: https://github.com/gazebosim/gz-gazebo/

Any idea on what's going on there?

**Comment by acxz** [comment]
I think the name has been changed to `gz-sim`: https://github.com/gazebosim/gz-sim

**Comment by acxz** [comment]
Resolved with [07d2a6e](https://github.com/acxz/gazebo-arch/commit/07d2a6e0fb9fafa68e90d6bf8a75872de27a1b6c)
