### ISSUE TITLE
legacy ignition-cmake(version 2.16.0) package required

### ISSUE THREAD

**Issue by cybaol** [acxz/gazebo-arch#46]
Legacy `ignition-cmake-2`(version 2.16.0)  package required by `ignition-common-3`, `ignition-fuel_tools-4`, `ignition-msgs-5`, `ignition-transport-8` , `gazebo`. Please add it to repository and update dependency.
,
Plus, `ignition-math-6`(version 6.13.0) package  also need `ignition-cmake-2` and required by `gazebo`.

**Comment by muellerbernd** [comment]
Hey @cybaol I had the same problem and created those legacy packages. They can be found in my repo: https://github.com/muellerbernd/my_arch_packages . @acxz feel free to include these legacy packages.

**Comment by acxz** [comment]
sorry was on vaycay just now getting back to gh

@muellerbernd thanks for providing PKGBUILDs in the meanwhile!

in the future, feel free to make PRs to this repo!

Done with fd9b851
