### ISSUE TITLE
/usr/bin/gz exists in both 'ignition-tools' and 'gazebo'

### ISSUE THREAD

**Issue by petronny** [acxz/gazebo-arch#51]
Which leads to some packages that depend on both of them fail to build.

https://github.com/arch4edu/cactus/actions/runs/4324667850/jobs/7549803120#step:15:977

**Comment by muellerbernd** [comment]
I can confirm. With ignition-tools version 1.5.0 it builds without an error.

**Comment by jannesklee** [comment]
I also have the error. What can I do in order to make the installation work. Should I downgrade to ignition-tools 1.5.0 or is there a more elegent way?

**Comment by jannesklee** [comment]
I simply used --overwrite /usr/bin/gz. Its no clean solution but at the moment gazebo runs (I am a very beginner and simply want to try out some things)

**Comment by acxz** [comment]
@petronny I believe I have resolved the issue, by adding a conflicts of `gazebo` on `ignition-tools`. I have also update several other packages to correctly refer to `ignition-tools-1` as needed.

Let me know if this resolves the issue.

**Comment by petronny** [comment]
Thanks! Problem solved.

**Comment by acxz** [comment]
Sweet! closing this issue for now.
