### ISSUE TITLE
'd' was not declared in this scope. 

### ISSUE THREAD

**Issue by jackleberryfin** [acxz/gazebo-arch#61]
Target build : ignition-common-3 (3.15.1-2)

For me this issue is in addition to #56 and #57. 

I was able to continue with the build after removing these sections of preprocessor sections of code. 

![Screenshot from 2023-03-16 02-34-34](https://user-images.githubusercontent.com/82206690/225378813-15135acf-7e05-4fb2-811c-7cea390e1617.png)

![Screenshot from 2023-03-16 02-35-21](https://user-images.githubusercontent.com/82206690/225378847-b19a7b37-717a-4de2-b604-6ad9abe38c7d.png)

**Comment by jackleberryfin** [comment]
I'm a bit of a newb and its probably quite likely that this version i'm building is not the latest.. and has been patched already.. The problem is this version is a dependency in ros-noetic

**Comment by muellerbernd** [comment]
@jackleberryfin ignition-common-3 is a dependency to gazebo and this is a dependency to ros-noetic-gazebo* . But at the moment the gazebo in AUR does not use the patched version. As soon as #54 is merged it should work.

**Comment by acxz** [comment]
In the time being you can use `gazebo-git` instead of `gazebo`.

**Comment by acxz** [comment]
`gazebo` has been updated, give it another shot @jackleberryfin

**Comment by acxz** [comment]
Closing as dup of #56

also please make sure to post codeblocks rather than images so that we can search through code
