### ISSUE TITLE
[gazebo] Can't find zmq.hpp

### ISSUE THREAD

**Issue by ripxorip** [acxz/gazebo-arch#67]
Hi great work with the package. 

It no longer compiles on my system as its looking for zmq.hpp while I have zmq.h under /usr/include/* 

Is this a known error?

**Comment by lounick** [comment]
I also have something similar. ignition-transport fails to build as CMake complains that can't find cppzmq. It must be added as a dependency. For now you can install it manually using `pacman -S cppzmq`.

**Comment by ripxorip** [comment]
That makes sense, thank you @lounick
