### ISSUE TITLE
[ignition-gazebo] Update AUR Package to Gazebo Sim 8?

### ISSUE THREAD

**Issue by frederikstroem** [acxz/gazebo-arch#87]
[Gazebo Sim 8 has been released](https://www.openrobotics.org/blog/2023/9/26/gazebo-harmonic-released) and is [available on GitHub](https://github.com/gazebosim/gz-sim/releases/tag/gz-sim8_8.0.0). In light of this update, I am curious if there are any plans to upgrade the `ignition-gazebo` [AUR package](https://aur.archlinux.org/packages/ignition-gazebo) to the latest version?

I would be happy to help with the update if needed.

Thanks in advance! 😊

**Comment by acxz** [comment]
Hello @frederikstroem of course we'd like to update Gazebo! Thanks for pointing out the new release. I've been a bit out of the loop with the robotics packages lately, so I apologize.

**Comment by acxz** [comment]
Closed with 6f70bdc
